services:
  - type: web
    name: number-guesser-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://NETLIFY_URL_PLACEHOLDER.netlify.app  # update after Netlify deploy
